language: java
jdk:
- openjdk6
script:
- ant -lib org.ant4eclipse.build/libs -f org.ant4eclipse.build/build-ant4eclipse.xml
  build.ant4eclipse
- ant -lib org.ant4eclipse.build/libs -f org.ant4eclipse.build/test-ant4eclipse.xml
  tests.ant4eclipse
before_deploy:
- export RELEASE_PKG_FILE=$(ls org.ant4eclipse.build/destination/org.ant4eclipse_*)
- echo "deploying $RELEASE_PKG_FILE to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: Xy2Lz54l3K4zAg0QnGig1amkNa+3z3nNS1eHg/wSdRfw35QahW2ZkjdVbeVhQLVJoEwy7FAm3TVNqVyyJN9Q+pJfMuqnQF4MReQ1U4jZDWyIGgkEPVq1olmHc+BQDJt50yqDaRqueU11mjodxemDcMytvcW5QOIIg1AVqjmjYv8=
  file_glob: true
  file: "org.ant4eclipse.build/destination/org.ant4eclipse_*"
  skip_cleanup: true
  on:
    repo: ant4eclipse/ant4eclipse
    tags: true
