/**********************************************************************
 * Copyright (c) 2005-2008 ant4eclipse project team.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Nils Hartmann, Daniel Kasmeroglu, Gerd Wuetherich
 **********************************************************************/
package org.ant4eclipse.core.exception;

public class ExceptionCode {

  private String _message;

  protected ExceptionCode(String message) {
    this._message = message;
  }

  public String getMessage() {
    return this._message;
  }

  /**
   * @generated by CodeSugar http://sourceforge.net/projects/codesugar
   */

  @Override
  public String toString() {
    StringBuffer buffer = new StringBuffer();
    buffer.append("[ExceptionCode:");
    buffer.append(" _message: ");
    buffer.append(this._message);
    buffer.append("]");
    return buffer.toString();
  }

}
